export APP__DATABASE_HOST=${MYSQL_PORT_3306_TCP_ADDR}
export APP__DATABASE_PORT=${MYSQL_PORT_3306_TCP_PORT}
export APP__DATABASE_NAME=${MYSQL_ENV_MYSQL_DATABASE}
export APP__DATABASE_USER=root
export APP__DATABASE_PASSWORD=${MYSQL_ENV_MYSQL_ROOT_PASSWORD}
